export const REGISTER_REQUEST="REGISTER_REQUEST";
export const REGISTER_SUCCESS="REGISTER_SUCCESS";
export const REGISTER_FAILURE="REGISTER_FAILURE";

export const LOGIN_REQUEST="LOGIN_REQUEST";
export const LOGIN_SUCCESS="LOGIN_SUCCESS";
export const LOGIN_FAILURE="LOGIN_FAILURE";

export const GET_USER_REQUEST="GET_USER_REQUEST";
export const GET_USER_SUCCESS="GET_USER_SUCCESS";
export const GET_USER_FAILURE="GET_USER_FAILURE";

export const ADD_TO_BOOKMARKED_SERIES_REQUEST="ADD_TO_BOOKMARKED_SERIES_REQUEST";
export const ADD_TO_BOOKMARKED_SERIES_SUCCESS="ADD_TO_BOOKMARKED_SERIES_SUCCESS";

export const ADD_TO_LIKED_CHARACTERS_REQUEST="ADD_TO_LIKED_CHARACTERS_REQUEST";
export const ADD_TO_LIKED_CHARACTERS_SUCCESS="ADD_TO_LIKED_CHARACTERS_SUCCESS";

export const ADD_TO_LIKED_EVENTS_REQUEST="ADD_TO_LIKED_EVENTS_REQUEST";
export const ADD_TO_LIKED_EVENTS_SUCCESS="ADD_TO_LIKED_EVENTS_SUCCESS";

export const ADD_TO_LIKED_CREATORS_REQUEST="ADD_TO_LIKED_CREATORS_REQUEST";
export const ADD_TO_LIKED_CREATORS_SUCCESS="ADD_TO_LIKED_CREATORS_SUCCESS";

export const ADD_TO_LIKED_COMICS_REQUEST="ADD_TO_LIKED_COMICS_REQUEST";
export const ADD_TO_LIKED_COMICS_SUCCESS="ADD_TO_LIKED_COMICS_SUCCESS";

export const CHECK_ITEM_BOOKMARKED_REQUEST="CHECK_ITEM_BOOKMARKED_REQUEST";
export const CHECK_ITEM_BOOKMARKED_SUCCESS="CHECK_ITEM_BOOKMARKED_SUCCESS";
export const CHECK_ITEM_BOOKMARKED_FAILURE="CHECK_ITEM_BOOKMARKED_FAILURE";

export const CHECK_ITEM_LIKED_REQUEST="CHECK_ITEM_LIKED_REQUEST";
export const CHECK_ITEM_LIKED_SUCCESS="CHECK_ITEM_LIKED_SUCCESS";
export const CHECK_ITEM_LIKED_FAILURE="CHECK_ITEM_LIKED_FAILURE";

export const ADD_TO_FAVORITED_CHARACTERS_REQUEST = "ADD_TO_FAVORITED_CHARACTERS_REQUEST";
export const ADD_TO_FAVORITED_CHARACTERS_SUCCESS = "ADD_TO_FAVORITED_CHARACTERS_SUCCESS";

export const ADD_TO_FAVORITED_EVENTS_REQUEST = "ADD_TO_FAVORITED_EVENTS_REQUEST";
export const ADD_TO_FAVORITED_EVENTS_SUCCESS = "ADD_TO_FAVORITED_EVENTS_SUCCESS";

export const ADD_TO_FAVORITED_CREATORS_REQUEST = "ADD_TO_FAVORITED_CREATORS_REQUEST";
export const ADD_TO_FAVORITED_CREATORS_SUCCESS = "ADD_TO_FAVORITED_CREATORS_SUCCESS";

export const ADD_TO_FAVORITED_COMICS_REQUEST = "ADD_TO_FAVORITED_COMICS_REQUEST";
export const ADD_TO_FAVORITED_COMICS_SUCCESS = "ADD_TO_FAVORITED_COMICS_SUCCESS";

export const CHECK_ITEM_FAVORITED_REQUEST = "CHECK_ITEM_FAVORITED_REQUEST";
export const CHECK_ITEM_FAVORITED_SUCCESS = "CHECK_ITEM_FAVORITED_SUCCESS";
export const CHECK_ITEM_FAVORITED_FAILURE = "CHECK_ITEM_FAVORITED_FAILURE";

export const UNBOOKMARK_ITEM_SUCCESS="UNBOOKMARK_ITEM_SUCCESS";
export const UNBOOKMARK_ITEM_FAILURE="UNBOOKMARK_ITEM_FAILURE";

export const GET_BOOKMARKED_ITEMS_REQUEST="GET_BOOKMARKED_ITEMS_REQUEST";
export const GET_BOOKMARKED_ITEMS_SUCCESS="GET_BOOKMARKED_ITEMS_SUCCESS";
export const GET_BOOKMARKED_ITEMS_FAILURE="GET_BOOKMARKED_ITEMS_FAILURE";

export const UNLIKE_ITEM_SUCCESS="UNLIKE_ITEM_SUCCESS";
export const UNLIKE_ITEM_FAILURE="UNLIKE_ITEM_FAILURE";

export const UNFAVORITE_ITEM_SUCCESS="UNFAVORITE_ITEM_SUCCESS";
export const UNFAVORITE_ITEM_FAILURE="UNFAVORITE_ITEM_FAILURE";

export const LOGOUT="LOGOUT";