export const REGISTER_REQUEST="REGISTER_REQUEST";
export const REGISTER_SUCCESS="REGISTER_SUCCESS";
export const REGISTER_FAILURE="REGISTER_FAILURE";

export const LOGIN_REQUEST="LOGIN_REQUEST";
export const LOGIN_SUCCESS="LOGIN_SUCCESS";
export const LOGIN_FAILURE="LOGIN_FAILURE";

export const GET_USER_REQUEST="GET_USER_REQUEST";
export const GET_USER_SUCCESS="GET_USER_SUCCESS";
export const GET_USER_FAILURE="GET_USER_FAILURE";

export const ADD_TO_LIKED_CHARACTERS_REQUEST="ADD_TO_LIKED_CHARACTERS_REQUEST";
export const ADD_TO_LIKED_CHARACTERS_SUCCESS="ADD_TO_LIKED_CHARACTERS_SUCCESS";

export const ADD_TO_LIKED_SERIES_REQUEST="ADD_TO_LIKED_SERIES_REQUEST";
export const ADD_TO_LIKED_SERIES_SUCCESS="ADD_TO_LIKED_SERIES_SUCCESS";

export const CHECK_ITEM_LIKED_REQUEST="CHECK_ITEM_LIKED_REQUEST";
export const CHECK_ITEM_LIKED_SUCCESS="CHECK_ITEM_LIKED_SUCCESS";
export const CHECK_ITEM_LIKED_FAILURE="CHECK_ITEM_LIKED_FAILURE";

export const UNLIKE_ITEM_SUCCESS="UNLIKE_ITEM_SUCCESS";
export const UNLIKE_ITEM_FAILURE="UNLIKE_ITEM_FAILURE";

export const LOGOUT="LOGOUT";